name: "build and Release"
on:
  pull_request:
    branches:
      - dev
      - test
  push:
    branches:
      - dev
      - test
      - main
  jobs:
    build:
      name: Build and Release
      runs-on: macos-latest

      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3

        - name: setup java
          uses: actions/setup-java@v3.12.0
          with:
            distribution: "oracle"
            java-version: '17'

        - name: setup Flutter
          uses: subosito/flutter-action@v2
          with:
            flutter-version: '3.7.5'
            channel: 'stable'

        - name: install dependencies
          run: flutter pub get

        - name: test flutter app
          run: flutter test

        - name: build apk
          run: flutter build apk --release

        - name: build appbundle
          run: flutter build appbundle

        - name: build ipa
          run: flutter build ipa --no-codesign
        - name: compress archives and Ipas
          run: |
            cd build 
            tar -czf ios_build.tar.gz ios

        - name: upload artifacts
          uses: actions/upload-artifact@v2
          with:
            name: Releases
            path: |
              build/app/outputs/flutter-apk/app-release.apk
              build/app/outputs/bundle/release/app-release.aab
              build/ios_build.tar.gz




